/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TTableIdRouteImport } from './routes/t.$tableId'
import { Route as TTableIdTipRouteImport } from './routes/t.$tableId.tip'
import { Route as TTableIdReceiptRouteImport } from './routes/t.$tableId.receipt'
import { Route as TTableIdCheckoutRouteImport } from './routes/t.$tableId.checkout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TTableIdRoute = TTableIdRouteImport.update({
  id: '/t/$tableId',
  path: '/t/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const TTableIdTipRoute = TTableIdTipRouteImport.update({
  id: '/tip',
  path: '/tip',
  getParentRoute: () => TTableIdRoute,
} as any)
const TTableIdReceiptRoute = TTableIdReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => TTableIdRoute,
} as any)
const TTableIdCheckoutRoute = TTableIdCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => TTableIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/t/$tableId': typeof TTableIdRouteWithChildren
  '/t/$tableId/checkout': typeof TTableIdCheckoutRoute
  '/t/$tableId/receipt': typeof TTableIdReceiptRoute
  '/t/$tableId/tip': typeof TTableIdTipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/t/$tableId': typeof TTableIdRouteWithChildren
  '/t/$tableId/checkout': typeof TTableIdCheckoutRoute
  '/t/$tableId/receipt': typeof TTableIdReceiptRoute
  '/t/$tableId/tip': typeof TTableIdTipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/t/$tableId': typeof TTableIdRouteWithChildren
  '/t/$tableId/checkout': typeof TTableIdCheckoutRoute
  '/t/$tableId/receipt': typeof TTableIdReceiptRoute
  '/t/$tableId/tip': typeof TTableIdTipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/t/$tableId'
    | '/t/$tableId/checkout'
    | '/t/$tableId/receipt'
    | '/t/$tableId/tip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/t/$tableId'
    | '/t/$tableId/checkout'
    | '/t/$tableId/receipt'
    | '/t/$tableId/tip'
  id:
    | '__root__'
    | '/'
    | '/t/$tableId'
    | '/t/$tableId/checkout'
    | '/t/$tableId/receipt'
    | '/t/$tableId/tip'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TTableIdRoute: typeof TTableIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tableId': {
      id: '/t/$tableId'
      path: '/t/$tableId'
      fullPath: '/t/$tableId'
      preLoaderRoute: typeof TTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$tableId/tip': {
      id: '/t/$tableId/tip'
      path: '/tip'
      fullPath: '/t/$tableId/tip'
      preLoaderRoute: typeof TTableIdTipRouteImport
      parentRoute: typeof TTableIdRoute
    }
    '/t/$tableId/receipt': {
      id: '/t/$tableId/receipt'
      path: '/receipt'
      fullPath: '/t/$tableId/receipt'
      preLoaderRoute: typeof TTableIdReceiptRouteImport
      parentRoute: typeof TTableIdRoute
    }
    '/t/$tableId/checkout': {
      id: '/t/$tableId/checkout'
      path: '/checkout'
      fullPath: '/t/$tableId/checkout'
      preLoaderRoute: typeof TTableIdCheckoutRouteImport
      parentRoute: typeof TTableIdRoute
    }
  }
}

interface TTableIdRouteChildren {
  TTableIdCheckoutRoute: typeof TTableIdCheckoutRoute
  TTableIdReceiptRoute: typeof TTableIdReceiptRoute
  TTableIdTipRoute: typeof TTableIdTipRoute
}

const TTableIdRouteChildren: TTableIdRouteChildren = {
  TTableIdCheckoutRoute: TTableIdCheckoutRoute,
  TTableIdReceiptRoute: TTableIdReceiptRoute,
  TTableIdTipRoute: TTableIdTipRoute,
}

const TTableIdRouteWithChildren = TTableIdRoute._addFileChildren(
  TTableIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TTableIdRoute: TTableIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
